pipeline:
  verify-lint:
    image: quay.io/presslabs/gitfs-test:3.11
    commands:
      - pip3 install ruff
      - make verify-lint

  test:
    image: quay.io/presslabs/gitfs-test:3.11
    privileged: true
    environment:
      - PIP_DOWNLOAD_CACHE=/tmp/pip_download_cache
      - PYTHON=${PYTHON_VERSION}
    commands:
      - chmod 660 /dev/fuse
      - echo user_allow_other | tee -a /etc/fuse.conf > /dev/null
      - chmod 644 /etc/fuse.conf
      - git config --global user.email "drone@example.com"
      - git config --global user.name "Drone CI"
      - make test
    volumes:
      - /var/cache/apt/:/var/cache/apt/
