FROM ubuntu:22.04

ARG PYTHON=3.11

RUN apt-get update && \
    apt-get install -qy build-essential software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    add-apt-repository ppa:presslabs/gitfs && \
    apt-get update && \
    apt-get install -qy python${PYTHON} python${PYTHON}-dev python${PYTHON}-venv python3-pip libfuse-dev fuse git libffi-dev libgit2-dev

COPY test_requirements.txt requirements.txt /
RUN pip3 install -r /test_requirements.txt
