name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
      
    - name: Run linting
      run: make verify-lint

  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          software-properties-common \
          fuse \
          libfuse-dev \
          git \
          libffi-dev \
          libgit2-dev \
          python3-pip
          
    - name: Configure FUSE
      run: |
        sudo chmod 666 /dev/fuse
        echo 'user_allow_other' | sudo tee -a /etc/fuse.conf > /dev/null
        sudo chmod 644 /etc/fuse.conf
        
    - name: Configure Git
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
        
    - name: Set environment variables
      run: |
        echo "PIP_DOWNLOAD_CACHE=/tmp/pip_download_cache" >> $GITHUB_ENV
        echo "PYTHON=${{ matrix.python-version }}" >> $GITHUB_ENV
        
    - name: Run tests
      run: make test