name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python 3.11
      run: uv python install 3.11
      
    - name: Run linting
      run: make verify-lint

  test:
    name: Test (Python 3.11)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Set up Python 3.11
      run: uv python install 3.11
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          software-properties-common \
          fuse \
          libfuse-dev \
          git \
          git-lfs \
          libffi-dev \
          libgit2-dev \
          python3-pip
          
    - name: Configure FUSE
      run: |
        sudo chmod 666 /dev/fuse
        echo 'user_allow_other' | sudo tee -a /etc/fuse.conf > /dev/null
        sudo chmod 644 /etc/fuse.conf
        
    - name: Configure Git
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git config --global init.defaultBranch main
        
    - name: Install Python dependencies
      run: |
        uv sync --extra test
        uv sync --extra dev
        
    - name: Set environment variables
      run: |
        echo "UV_CACHE_DIR=/tmp/.uv-cache" >> $GITHUB_ENV
        echo "PYTHON=3.11" >> $GITHUB_ENV
        
    - name: Run tests
      run: make test